#include<bits/stdc++.h>
#define ri register int
#define ll long long
using namespace std;

int read()
{
	int num=0;
	int flg=1;
	char c=getchar();
	while(!isdigit(c))
	{
		if(c=='-')
		{
			flg=-1;
		}
		c=getchar();
	}
	while(isdigit(c))
	{
		num=(num<<1)+(num<<3)+(c^48);
		c=getchar();
	}
	return num*flg;
}

const int maxn=1e6+7;
struct edge
{
	int to;
	int nex;
} e[maxn];

int cnt=0;
int head[maxn];
void add(int u,int v)
{
	e[++cnt].to=v;
	e[cnt].nex=head[u];
	head[u]=cnt;
}

int n,m;
int rd[maxn];
int Q[maxn];
int tot=0;
void topo()
{
	queue <int> q;
	for(ri i=1; i<=n; i++)
	{
		if (rd[i]==0)
		{
			q.push(i);
			Q[++tot]=i;
		}
	}
	while (q.size())
	{
		int top=q.front();
		q.pop();
		for(ri i=head[top]; i; i=e[i].nex)
		{
			int to=e[i].to;
			rd[to]--;
			if (rd[to]==0)
			{
				q.push(to);
				Q[++tot]=to;
			}
		}
	}
}

int f[maxn];
int main()
{
	n=read();
	m=read();
	fill(f+1,f+n+1,1);
	for(ri i=1; i<=m; i++)
	{
		int u=read();
		int v=read();
		add(u,v);
		rd[v]++;
	}
	topo();
	for(ri i=1; i<=n; i++)
	{
		int top=Q[i];
		for(ri j=head[top]; j; j=e[j].nex)
		{
			int to=e[j].to;
			f[to]=max(f[to],f[top]+1);
		}
	}
	for(ri i=1; i<=n; i++)
	{
		printf("%d\n",f[i]);
	}
}

/*
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLiKDGGGDGGGGGDKGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLfGGGGGGGGGGGGGGGGGjLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLKfLGGGGGGGGGGGGGGGGDGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL;ffGGGGGGGGGGGGGGGGGGGDGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLjjfGGGGGGGGGGGGGGGGGGGGGDGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLKfLGGGGGGLDGGGGGGGGGGGLGGGDGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLKfLLGGGGGGEDGGGGGGGGGGGGLGGGGGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLfLfGGGGGGLDGGGGGGGGGGGGGGGGGGGGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLfffLGGGGGGfDGGGGGGGGGGGGGGGGGGDGGGKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLfffGGGGLGLDDGGGGGGGGGGGGGGGLGGGEGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLfffGGGGLGGfEDLGLGGGGGGGGGGGGDGGGGGGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLtLLLLLLLLLLLLLLGfffGGGGffffDGLGLGGGGGGGGGGGGGfGGGEGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLKELLLLLLLLLLLLLffLDGGGGfffLDGfGLLLGGGGGGGGGGGDGGGGDGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLE:;LLLLLLLLLLLDLGfGGGGGLffEDGfGLLfLGGGGGGGGGGGfGGGGGGGELLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLD:,LLLLLLLLLLLfGGfGGGGGGLLEDGfGGLGfGGGGGGGGGGGDLGGGEGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLD::DLtGEKLLLLKfGGDGGGGGGGfDDGfGGLLLLLLLLLLLGGGGLGGGGGGGWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLDE;.;:::KLLLLfGGLEGGDGGGGfDGGLGLLLLLLLLLLLLLLGGDGGGGGGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLK;.:G::::.:KLLLLLfGGGGGGGGGGGfDGLDLLLLLLLLfLLLLLLLLDfGGGDGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLL;G::::EKLLLLLWGGGGGGGGGGGGfDGLjLLLLLLLLfLLLLLLGLDGGGGGGGGKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLDi:::fLLLLLLEGGGGGGGGGGGGfDGG,fLLLLLLLLLLLLLLGLGDGGGGGGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLf:,fj:,LLLLLfGGGDGGGDGGGGfDLE,LLLLLLLLLLLLLLLDGLDLGGGGGGGWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLf::KLK.,LLLLGGGGDGGGGGGGGfDLG:fGLLLLLLLfLLLLLLDGDGGGGGGGGELLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLf:;LLLtEELLtGGGGEGGGGGGGGfDLj. GLLLLLLLGLLLLLLLGDGLGGGDGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLL:LLLLLLLLLEGGGGEGGGGGGGGfDLf  LLLLLLLLtfLLLLL:GDGLGGGGGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLGLLLLLLLLLLGGGGGEGGGGGGGLLDG,: DDLLLLLLfLLLLLLjEGDGLGGGDGDWLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLGGGGGEGGGGGGGLLDD,  L,LLLLLLEjGLLLLDjGDDLGGGDGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLGGDGGDGGGGGGLLLDD,   KDLLLLLL.DLLLLE:KDDLGGGGDGDKLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLDGGGGGDGGGGGGLLLDD,   .:ELLLLL,fDGLLD,LDDGGGGGDGDDWLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLDDGGGGGGGGGGDGLLLDE.      j.j::  .,,,,,jEEELGGGDDDDDLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLL;iGGGGGGGGGGGEGLLL,. LKEEEKE             ,,fLGGGGDDWDKLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLGGGDGGGGDGGGDGLLL,:KEDKKjDD               fDGGGGDDjKDLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLDLGGGGDGGDGEGGGGGLLL,ED;KDD:::        ;,    GfGGGGGEDKLDELLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLfLLGGLGDGGDGDGGGGGLLLD:EDEEG,         : KKEG LffGGGGGDELLDLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLDjLLjGEGGDGGLGDGGGGLLLLL EGLGL           KEDLG.fffGGGGGGELLEELLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLttLLLLLEGLKGDGGfGDGGGGGGLLE,f::.i          ,     EfLfEGGDGDELLLGWLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLGGLEGDGGfGGDGGGDGLLE. ,;,                 GffLfGGDGEGLLLKDLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLtGELEGDGGEEGDGGGDGGLG:                     fffLfGGDDEELLLLGLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLGELKGGDGEDDDGGGDGGLL,  .                  ffffLEGGDEKLLLLKWLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLKGEGGGDGGDDDGGGDGGGLf   .                :LfffffGGDEjLLLLLELLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLGGDDGDDGDDDEGGGDGGGK          tLj       DfDffffGGGELLWLLLGLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLGGGGDGDGEDDEGGGDGGGG.       fiiiiK      fffffffGGGDLLGLLLGLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLtDDDDDGDDDEEDEGGDGGGL:       iiiiii    :ffffDfffDGGKLLLLLLGLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLKDEDGGGGDDDDDDDGDDGGGG       iiiii    tDDffffLffDGGKLLGLLLDLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLEDGGGGGGGGGEEDEDGDGGGD,L      iiL    KDDDffffWffLGGKLLGLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLDDGGGGGGGGGGGGDDDGDGGGG,,,j         ,DDDDDEfffDWffGGELLDLLGLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLEGGGGGGEGGDEGGGGGEDDDGGGj,,,,tj     DDDDEDDDffffLKfGGGLLLLL;LLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLDGGGGDEGGGGDDDGGGGEG EGGG:  ,,,,EKDDDDDDDDDDEfGfLLfGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLDGGGDDGGGGGGGDDGGGD  EGGGE,   :EDDDDDDDDDDDDDKDfLLGGGGLGLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLKGGDDGGGGGGGGGDDGGE  DDGGG;   GGDDDGGDDDDDDGGGWfWLWGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLDDDDGGGGGGGGGGDDGE  EDGGGG,  ,,EGGGGGGDDEGGGGWDLLLGDDLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLDDDGGGGGGGGGD,LDDE  EGEGGGG: :,:GGGGGGDEGGGGGKELLWGGELLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLKDKGGGGGGGGL    DE  EGGEGGGG;:t,DGGGGDDGGGGGGKELLKGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLDDGGGGGGGE      D  GGGGDGfGGK ,GGGGGDDGGGGGGLWLLGLELLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLGGGGGGGGGL     E: tGGGGGEi,GEGiGGGDGGGGGGGDLLLLLGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLWGGGGGGGGGGGK:  L,,,EGGGGDf.::.iGGGEGGGGGGGKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLEGGGDGGGGGGGGE  .i,,iDGGGDD,  .EGGEGGGGGGGWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLDGGGDGGGGGGGD.   .,,,DDGGDDE  :GGDGG LGGEDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLjGGGGGGGGGGGG      L,,DEDGDDD  DGDGt  EEDDDELLLLLLLLLLLLLKLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLWGGGGGDGGGGGE     ,,D;DDEGDDD,EGGGG   EDDDDGLLLLLLLLLLLLL:tLLtLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLEGGGGGDDGGGGK  j;. LGEDEEEDDEDDGGGD  EDDGGGGKLLLLLLLLLLL;Lf::DLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLDGGGGGGDDGGDGE     .fDDDDDDDEDGGGGK  DGDGGGGDLLLLLLLLLEi;::fKLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLGGGGGGGDDDGDGE     ;,GDDDDDDEDGGEDE  GGDGGGGGLLLLLLLLLLGt::jKLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLGGGGGGGGEDGDGL   L. KGGDDDDDDDGEDDf  GKKGGGGGLLLLLLLLLLLiE,,:LLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLGGGGGGGGGDDGGDK.    GGGEDEEDEDDEDD .;    fGGGKLLLLLLLLLL;:KjKiLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLGGGGGGGGGDDGGGED   EGGGDDDDDDDDGD   i     GGGDLLLLLLLLLLLKLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLKGGGGGGGGGGDDGGED.LGGGGGDGDDDDDEGD          GGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLGGGGGGGGGGGGDGGGGGGGGGGGGGDDEDGGGE i  f t  .GGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLGGGGGGGGGGGDGGGGEGGGGGDGGGEDDDGGEE,     fDEEGGGGKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLGGGGGGGGGDDDGGGGGDGGDGGGGGDEDEGGDK,      EEGDGGGGKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLGGGGGGGGGDDGGGGGGGDDGGGGGGDEGGGGD;  L    DEGGEGGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLDGGGGGGGDDGDGGGGGGGGGGGGGEDEGGDGGL      GDEGGGGGGGDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLKGGGGGGGDGGEGGGGGGGGGGGGGDDDGGEGGf      EDEGGGEGGGGKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLEGGGGGGEDGGGGGGGGGGGGGGGDDDGGGEDG  i    EDDGGGDGGGGGfLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLGGGGGGGDGGEGGGGGGGGGGGGGEDGGGGDDG   :  tGEGGGGGGGGGGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLEGGGGGDDGGDGGGGGGGGGGGGGDDGGEGDGGK    EGGGGGGGGDGGGGGELLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLKGGGGGDGGEDGGGGGGGGGGGGKDDGGGEDGDGG   GGGGGGGGGEGDGGGDfLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLEGGGGGDGGDGGGGGGGGGGGGGDDGGGGEDGGEGDjDEGGGGGGGGDGGEGGGELLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLGGGGGDGGDDDGGGGGGGGGGGEDDGGGGDEGDGDEEDGGGGGGGGGGDGGDGGDKLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLGGGGGGGDDDGGGGGGGGGGDDDGGGGGGEGGGGGGGGGGGGGGGGGEDGGDDDDLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLGGGGGGGDDDGGGGGGGGGGEDDGGGGGGEGGEGGGGGGGGGGGGGGDEGGGDDDLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLDDDGGGGGDDGGGGGGGGGEEDDGGGGGGGGGGGGGGGGGGGGGGGGDDDGGDDDELLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLj;DDDDDDDD;DDDDDDDWjLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
*/
